experimentalTernaries: true
printWidth: 110
tabWidth: 4
useTabs: true
singleQuote: true
jsxSingleQuote: true
trailingComma: "es5"
bracketSpacing: true
bracketSameLine: false
proseWrap: "always"
plugins: ["prettier-plugin-tailwindcss"]
