#!/usr/bin/env bash

if [ "$(id -u)" -ne 0 ]
then echo "Run me again as root."
    exit
fi

printf "\nUpdating apt repositories... \n"
apt-get update && apt-get upgrade

printf "\nPulling new image: \n"
git pull

printf "\nStopping running ctr: '$(docker ps --format {{.Names}})'\n"
docker stop $(docker ps -q) 1>/dev/null && printf "Done."

printf "\nbuilding image\n:"
docker build -t plsuwu .

printf "\nStarting service: "
docker run --rm -dp 80:3000 plsuwu


printf "\nUpdate finished.\n"
