experimentalTernaries: true
printWidth: 90
tabWidth: 4
useTabs: true
singleQuote: true
jsxSingleQuote: true
trailingComma: 'es5'
bracketSpacing: true
bracketSameLine: false
proseWrap: 'always'
plugins: ['prettier-plugin-svelte', 'prettier-plugin-tailwindcss']
overrides:
    - files: '*.svelte'
      options:
          parser: 'svelte'
